import Header from './components/Header'
import './styles/globals.css'

export const metadata = {
  title: 'Travel App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt_BR">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
